from _cffi_backend import FFI

ffi: FFI

class _Lib:
    def Twofish_initialise(self) -> None: ...
    def Twofish_prepare_key(self, key: bytes, key_len: int, xkey: FFI.CData) -> None: ...
    def Twofish_encrypt(self, xkey: FFI.CData, p: bytes, c: FFI.CData) -> None: ...
    def Twofish_decrypt(self, xkey: FFI.CData, c: bytes, p: FFI.CData) -> None: ...

lib: _Lib
